- package.json
- script/seed.js
- server/db/models/index.js
- server/db/models/product.js
- server/db/models/product.spec.js
* [ x] added unit tests (or none needed)
---
After creating databases for our project (fleuria and fleuria-test), we created a Product model. It contains name, description, price and imageUrl fields. We also created seed data to populate for testing purposes. We wrote tests to check the column pass our needs and required fields are present.
Closes #9
> Products model #9

- package-lock.json
- server/api/index.js
- server/api/products.js
- server/api/products.spec.js
---
We added the get all products route, as well as the test for the route.
> adds get all products route

- client/components/allProducts.js
- client/components/cart.js
- client/components/index.js
- client/components/navbar.js
- client/routes.js
- public/style.css
- server/index.js
Added links to nav bar and set up routes and placeholder component for allproducts and cart.
> navBar updates

- .travis.yml
- client/store/index.js
- client/store/product.js
- client/store/product.spec.js
* [ x] added unit tests (or none needed)
* [x ] written relevant docs (or none needed)
* [ x] referenced any relevant issues (or none exist)
---
Created files in store folder for product and product.test. 
- product.js sets up action creators and thunk creator to set all products in the store
- product.test.js provides testing that the correct actions are being dispatched and the correct data received
- updated store/index.js to import product store and include it in the combined reducer
> Product store #5

- package-lock.json
- server/api/products.js
- server/api/products.spec.js
---
This PR adds the get route for a single product, and also adds the test spec.
> complete get singleProduct route and test spec

- server/db/models/product.js
* [x ] referenced any relevant issues (or none exist)
Fixes a bug in the Product model that was preventing the imageUrl from loading in our routes.
> Fixed bug to allow imageUrl default value

- client/store/product.js
- client/store/product.spec.js
---
adds selectedProduct to store , create fetchSingleProduct thunk, and adds test spec unit
> adds selectedProduct to store, and adds test spec

- client/components/allProducts.js
- client/components/allProducts.spec.js
- client/components/index.js
---
I finally have the all products component view for you, though still without a test. I think the Link in there should work once the single product route is up.
> allProducts without a test

- client/components/cartUtilFunctions.js
- client/components/singleProduct.js
---
These utility functions will be used in the cart component. They've been tested and return number types like we need.
> cart utility functions

- server/db/models/index.js
- server/db/models/order-product.js
- server/db/models/order.js
- server/db/models/order.spec.js
---
refactor the order model to have the 'orderproduct' through table, but not finish the test spec
> refactor the order model to have the through table without the test spec

- server/db/models/user.js
We made it so that the address fields are not required.
> makes address fields in user model optional

- client/components/cart.js
- public/index.html
- public/style.css
---
Added total cost field and buttons to remove product from cart. Tweaked css styling.
> Cart component #26

- client/components/singleProduct.js
- public/style.css
- script/seed.js
---
Resolves image render issue for SingleProduct view and also adjusts css styling for the view.
> fixed imageUrl in seed file, adjusted css for singleProduct view

- client/components/cartUtilFunctions.js
- client/components/checkout.js
- client/components/checkoutForm.js
- client/routes.js
- public/style.css
Adds Checkout view component. Still needs submit button added to the form.
> Checkout component #34

- client/components/modal.js
Added "Your item has been added to the cart!" message, and adjusted buttons accordingly. Changed text color to white and matched button background color with website theme.
> adjusted buttons and added confirmation text

- client/components/addQuantitytoCart.js
- client/components/cart.js
- client/components/modal.js
- client/components/singleProduct.js
- client/store/product.js
- public/index.html
- public/style.css
- script/seed.js
- server/api/products.js
post route working and cart in redux store updated
> Add cart routes #41

- client/components/checkout.js
- client/components/checkoutForm.js
- client/components/confirmation.js
- client/components/index.js
- client/routes.js
- public/style.css
Added submit button to checkout component and renders confirmation view upon click
> Cart component #67

- client/components/navbar.js
gives logout and home buttons the class name they need for styling
> nav bar fix

- client/components/checkoutForm.js
- client/components/modal.js
- public/style.css
Adjusts styling for modal component to align buttons and adjust color
> adjusted modal styling

- client/components/cart.js
- client/components/checkoutForm.js
- public/style.css
Adjust css for cart and checkout components
> adjusts cart and checkout styling

- client/components/user-home.js
- client/components/user-home.spec.js
Adjusted home render for user view so the image and text renders below the welcome message.
> Fix home render for users

- client/components/cart.js
- client/components/singleProduct.js
- client/store/product.js
- server/api/cart.js
- server/api/products.js
add put/get '/api/cart' route, add post/put '/api/products/:productId' route, also update the redux store
> Add put routefor d bcart #68

- client/components/cart.js
- client/components/checkout.js
Fixes issue with user's cart updating correctly.
> fixed cart component to get cart updates

- client/components/cart.js
- client/store/product.js
- server/api/cart.js
add removeFromDbCart thunk and route for delete from cart
> add removeFromDbCart thunk and route for delete from cart

- public/style.css
fixes white margin around body.
> fixes body margin

- client/components/user-home.js
- public/style.css
> adjust welcome message margin

- public/index.html
> adding meta tags for social media sites

- public/index.html
> Remove duplicate meta tags index.html
